import { Inter } from "next/font/google";
import { Sen } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});
const sen = Sen({ 
  subsets: ["latin"],
  display: 'swap',
  weight: ['600',]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sen.className}>{children}</body>
    </html>
  );
}
